files:
  - source: /language/en-GB/tpl_allrounder.sys.ini
    translation: /language/%locale%/tpl_allrounder.sys.ini
  - source: /language/en-GB/tpl_allrounder.ini
    translation: /language/%locale%/tpl_allrounder.ini
