files:
  - source: /tpl_allrounder/language/en-GB/tpl_allrounder.sys.ini
    translation: /tpl_allrounder/language/%locale%/tpl_allrounder.sys.ini
  - source: /tpl_allrounder/language/en-GB/tpl_allrounder.ini
    translation: /tpl_allrounder/language/%locale%/tpl_allrounder.ini
